### ISSUE TITLE
Add more searching samples

### ISSUE THREAD

**Issue by tiagosiebler** [MicroStrategy/web-sdk-samples#50]
- [ ] One sample searching for a configuration object (user or group)
- [ ] One sample searching for a project-level object (e.g a report)

https://github.com/MicroStrategy/web-sdk-samples/tree/master/stand-alone/com/microstrategy/samples/searching

**Comment by michaelScarfi** [comment]
Think this can be closed now

**Comment by tiagosiebler** [comment]
Thanks @michaelScarfi 

merged in #52
